apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-docs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : docs-server
    spec:
      containers:
        - name: docs-server
          image: satyamz/mdocs:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docs-service
  name: maya-docs-service
spec:
  type: NodePort
  ports:
  - name: doc-server
    port: 3000
    nodePort: 30551
    protocol: TCP
  selector:
    app: docs-server

